= Audio Library for Arduino Nano 33 IoT or SAMD based boards =

The SamdAudio library enables an Arduino Nano 33 IoT to playback mono 8bit .wav files 
from a storage device like an SD card, without blocking program execution.
Compatible with Atmel SAMD series MCU and is best used with DAC related amplifiers.

== Available Functions ==
    void selectShutdownPin(uint8_t shutdownPin);
        // select the pin to control amplifiers that contain shutdown pins (SD)
        
    void setShutdownPinState(bool pinState);
        // change the state of the shutdown pin of an amplifier
        
    void setShutdownPinState(bool pinState, bool muteAudio);
        // change the state of the shutdown pin of an amplifier while setting mute flag
        
    void selectDACPin(uint8_t audioOutputPin);
        // select the audio output pin on the microcontroller4
        
    void selectDigitalPotPin(uint8_t DigitalPotPin);
        // select the digital potentiometer pin on the microcontroller
    
    setBlocking(bool blockFlag);
        // enable or disable blocking mode to prevent code execution play() until audio track finishes, disabled by default
        
    void begin(uint32_t sampleRate, uint8_t numOfChannels, uint16_t audio_buffer_size); 
        // initates audio player. variables required are sample rate, number of channels to use, and audio buffer size
        
    void play(const char *fname, uint8_t channel);
        // to play a single track, used when multiple channels are necessary
        
    void play(const char *fname);
        // to play a single track, used when multiple channels are not necessary
        
    void stopChannel(uint8_t c);
        // called to stop a specific audio channel
        
    void loopChannel(uint8_t c, bool loopEnable);
        // sets a specific channel to be looped until stopped

    bool isPlaying(uint8_t c);
        // check to see if selected channel is playing
        
    void setGain(uint8_t v);
        // set initial volume, default set to 4 (shouldn't need if using hardware gain control)
        
    void gainUp();
        // increase volume (shouldn't need if using hardware gain control)
        
    void gainDown();
        // increase volume (shouldn't need if using hardware gain control)
        
    void setVolume(uint8_t v);
       // move the wiper of the digital potentiometer to the selected value from 0 to 100 (scaled to 0-255) (note, if using other SPI devices all pins will have to be set high first)
    
    void volumeUp();
        // decrement the wiper of the digital potentiometer by one (note, if using other SPI devices all pins will have to be set high first)
    
    void volumeDown();
        // increment the wiper of the digital potentiometer by one (note, if using other SPI devices all pins will have to be set high first)

    void end();
        // called to manually stop the audio player

== Tutorial ==
In the Player.ino file you will see an example that covers all relevant functions and procedures related to this library.  If you are not using a Class D amplifier with the Shutdown Pin (SD) then comment out the lines of code related to 'selectShutdownPin(shutdownPin)' and 'setShutdownPinState(pinState)' to avoid unintended behavior.  A video and picture filled, fun fantastic tutorial is coming soon!

== Why another library? ==
IMO, AudioZero (the library which is reffered to most often for newer Arduino's) absolutely sucks.  It's not maintained well and some pretty important bugs have not been addressed in years.

I found AloyseTech's library and thought this is perfect, almost.  Sdfat (as of Ver 2.0.5) doesn't play well with the Nano 33 IoT, so I changed the SD card driver to SD.h.  I added some good controls for Class D amplifiers that are commonly used.  A few more changes to go and this library will be your go-to for wav file playback! +
----
To-Do:
  o Add stereo playback (need help with this one)
  o Add native MP3 decoding
  o take le nap then fire Z MISSILES!
----

== Dependencies ==
MCP4XXX Library https://github.com/D34G/mcp4xxx (control of digital potentiometer circuits for amps with electronic control of gain)

== License ==

Copyright (c) D34G. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
